### PR TITLE
Add support for any n_components

### PR DESCRIPTION
**Pull request by DmitryUlyanov**

### CODE REVIEW

**Comment by DmitryUlyanov** [comment]
@kernc This PR does not pass the test you've recently changed https://github.com/DmitryUlyanov/Multicore-TSNE/pull/30/files#diff-3750794572d9fcc10dab7228fa9e8e43R28. However if `perplexity=5` it seems it passes. What was the reason for changing the test? Any ideas why it matters that much?

**Comment by kernc** [comment]
Please enable also AppVeyor. The test failed for me on 32bit Windows, I assume due to lower precision (but I wouldn't know to point where exactly as `double` should be `double` all the same).

**Comment by DmitryUlyanov** [comment]
Enabled it here https://ci.appveyor.com/project/DmitryUlyanov/multicore-tsne. 

Ok, it is strange. Don't know what 32-bit could change...

**Comment by kernc** [comment]
Well, since the push to your `1d` branch, and the OS X build both built and tested ok, I guess the test is indeterministic despite pinning of the random seed.

If you enabled AppVeyor, why hasn't the appveyor check run in this PR?
Ah, please rebase `1d` branch (and any older branches) onto the current master, i.e.
```bash
git checkout master
git pull  # sync with github master

git checkout 1d
git rebase master

git push -f
```

**Comment by kernc** [comment]
Why make all allocations on the heap? Surely the stack must be large enough for dozens of doubles (i.e. all sensible values of QT_NO_DIMS)?

**Comment by DmitryUlyanov** [comment]
My last experience with C/C++ was more than 3 years ago :) How do you allocate something dynamically on stack?

**Comment by kernc** [comment]
Not an expert myself. As I understand it, all local variables are allocated on stack, so:
```c
double array[10];  // local variable array of size 80 bytes
```
is allocated on stack as well as
```c
double *array = new double[10];  // a pointer of size 8 bytes
```
is allocated on stack, while the contents the pointer points to (80 bytes) is allocated on heap. Stack allocation is [usually faster](https://en.wikipedia.org/wiki/Stack-based_memory_allocation) and preferable for small variables.

Visual example: stepping through the [execution here](http://pythontutor.com/visualize.html#mode=display), stack allocations are (approximately) in the Frames column and heap allocations in the Objects column.

The maximum stack size is limited at link time by the OS (can be influenced, though), and is by default 8 MB on Unix and 1 MB on linux. So if you make a function that contains:
```c
double buff[qt_no_dims];
```
where `qt_no_dims` is assured some small value (i.e. 4), this takes 8*4=32 bytes, so you can only recurse such a function some 30 times on Windows. If the function isn't recursive, it pays in performance to put its variables on stack.

**Comment by kernc** [comment]
Perhaps tweak that naughty test a little. Sorry to have proposed an unreliable code. S:

**Comment by DmitryUlyanov** [comment]
I see, thank you. But to allocate something in the way `double array[10];` you need to know the size of the array at the compilation time. Maybe you are right and it is better to allocate it once of size 10 while using only `QT_NO_DIMS` values out of it.

**Comment by DmitryUlyanov** [comment]
Done here! Thanks @kernc!

**Pull request merged**
