### PR TITLE
Make 'packaging' a setup requirement

### PR DESCRIPTION
**Pull request by ecederstrand**
This allows installing MulticoreTSNE in an empty virtualenv.

### CODE REVIEW

**Comment by ecederstrand** [comment]
@DmitryUlyanov Do you think you could release a new version on PyPI containing this patch?

**Comment by jorvis** [comment]
@DmitryUlyanov If you add me as a co-owner on the PyPi project like you did here, I can do the release in both places.

**Comment by DmitryUlyanov** [comment]
@jorvis what is your id at PyPi?

**Comment by jorvis** [comment]
> @jorvis what is your id at PyPi?

Same as here, thanks!

https://pypi.org/user/jorvis/

**Comment by DmitryUlyanov** [comment]
Added!

**Comment by ecederstrand** [comment]
Any chance this could be released in a new package on PyPI?

**Comment by jorvis** [comment]
I keep lagging here. I'll see if I can do a release this weekend.

**Pull request merged**
