### PR TITLE
Fixes issue where setup was failing on cmake >= 3.22.0. Works with ve…

### PR DESCRIPTION
**Pull request by jorvis**
…rsions earlier and later.

### CODE REVIEW

**Comment by ecederstrand** [comment]
Ping @DmitryUlyanov I see this issue on Ubuntu 22.04. Can you merge this PR and carve a new release?

**Comment by DmitryUlyanov** [comment]
Merged, if anyone wants to become a maintainer for this library, I can add as collaborator. I don't have time to work on this any more.

**Comment by jorvis** [comment]
I rely on this library so don't mind be added, but my contributions would likely be limited to small fixes, releases, etc.

**Comment by DmitryUlyanov** [comment]
Hi @jorvis , sent you an invite. Feel free to do what you think is right. Small fixes are better than no fixes :)

**Pull request merged**
