### PR TITLE
Improve Windos compatibility and test on AppVeyor

### PR DESCRIPTION
**Pull request by kernc**
This PR ~~improves~~enables building on Windos, proved by example on AppVeyor. If you like it, consider enabling AppVeyor for this project. Two tests needed to be adapted a bit, I guess due to their imprecise, arbitrary-set constraints. I know not better.

Updated the readme to what seem to be the current build instructions. I don't think anything is needed besides cmake and a compiler. OpenMP is optional, pending compiler availability. Please feel free to edit as you see fit.

OpenMP requirement was loosened because recent MSVC compilers only support 2.0 version of that standard from 1998.

[AppVeyor example run](https://ci.appveyor.com/project/kernc/multicore-tsne-e1768).

-----

Would you be interested in maintaining this package also on PyPI? I'd be happy to follow up with a small addendum to Travis and AppVeyor recipes, which would result in you just needing to issue the following few steps to publish a new release, making it accessible to install on all (three) platforms:
```bash
git commit setup.py -m "bump version to 1.1 or whatever"
git tag 1.1
git push --tags
# The tagged commit build results would be automatically pushed to PyPI
```

### CODE REVIEW

**Comment by DmitryUlyanov** [comment]
Hi, thank you for the PR! Do you want me to enable both AppVeyor and Travis? From what I understang googling both are about the same. What is the benefit to have both on? 

Yes, I will be happy to maintain a package on PyPI!

**Comment by kernc** [comment]
Yes, both are continuous integration services, but whereas Travis only supports GNU/Linux and Mac OS X, AppVeyor only supports Windos. Need both to cover all three platforms.

Great, let me try to add the relevant bits to both recipes ...

**Comment by kernc** [comment]
The last commit introduces deploying to PyPI from Travis and AppVeyor. For Linux and OS X, only x64 wheels are provided, as available. The maintainer workflow that is supposed to work is:
```bash
vi setup.py  # Bump package version
git commit setup.py -m "bumped version to X.Y"
git tag X.Y

# This publishes the tag on GitHub, available from the branch-switcher drop-down.
# It also triggers the master-branch builds on CI services, and the two are
# configured to upload build source and binary packages to PyPI.
git push --tags
```
You need to configure `TWINE_USERNAME` and `TWINE_PASSWORD`:
* for AppVeyor in `.appveyor.yml` environment; encrypt them [here](https://ci.appveyor.com/tools/encrypt) beforehand.
* for Travis, you can do it in Travis project settings. Do [escape](https://docs.travis-ci.com/user/encryption-keys#Note-on-escaping-certain-symbols) any special characters in your password. This is [secure](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings).

The procedure was tested working, with sample blobs uploaded on https://pypi.python.org/pypi/MulticoreTSNE. The wheels were only partially tested, but I think they might indeed work.

Let me know your PyPI username.

**Comment by kernc** [comment]
If any tag builds ever fail to build (due to some unrelated CI error such as failure to download homebrew update on OS X, or Windows failing to pip-install twine, or some such error), you can [delete the remote tag](https://stackoverflow.com/questions/5480258/how-to-delete-a-git-remote-tag) and push it again, and it should work.

**Comment by DmitryUlyanov** [comment]
Thanks! 

Registered on PyPI, my username is `dulyanov`. 

Will merge today!

**Comment by kernc** [comment]
You're the owner (check online, I don't think PyPI sends any email). Left myself in just to ensure a stabler bus factor. Feel free to counter if you oppose.

Please go over everything thoroughly — I mostly don't know what I'm doing. 😃

**Comment by DmitryUlyanov** [comment]
Hi, it's easier to fix something when it is broken than think beforehand :wink:

**Pull request merged**
